server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT:3306}/mytask
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect